### PR TITLE
Add citations to STRchive-loci.json

### PR DESCRIPTION
**Pull request by hdashnow**
This is ready to merge now.

- allow check-loci to add literature and change output json formatting to reduce lines. 
- changed citations field issued_date -> date as expected on the website
- Manual fallback with biomart is down
- update scripts and workflow to add literature fields to loci json
- prettier json

### CODE REVIEW

**Comment by laurelhiatt** [comment]
it looks pretty good! the only thing, is I wonder if it could be useful to have the year in the citations?

**Comment by hdashnow** [comment]
@laurelhiatt can you poke around a few loci and check for weird formatting or missing data? I suspect we will have a few that failed manubot and so have minimal content.

**Comment by laurelhiatt** [comment]
I don't mind the genereviews, omim, mondo etc IDs redirecting to the cite. we do need a way to process the orphanet code for SBMA at least. spot checking the other pages now

**Comment by laurelhiatt** [comment]
i want to add to "Additional literature related to this locus." a sentence about how the full literature pull is available on Github as .txt. we could also add a Github redirect button to each locus's .txt file @vincerubinetti ?

**Comment by laurelhiatt** [comment]
edm1-psach_comp has genereviews listed twice. so we probably need to check the citations entries for internal redundancies in addition to check references against additional_literature

**Comment by laurelhiatt** [comment]
Screenshot 2024-12-03 at 8 10 30 PM
actually this is maybe just because of the weird way this locus plays out maybe...

**Comment by laurelhiatt** [comment]
double omim in references of DIP2B so issue in other loci also

**Comment by laurelhiatt** [comment]
genereviews 3 times in sca27b_fgf14, I have persuaded myself that this is an occurrence whenever a resource is mentioned multiple times

**Comment by laurelhiatt** [comment]
it does not process isbn:978-3-031-66932-3

**Comment by laurelhiatt** [comment]
doesn't process PMID: 35700120 in GIPC1, for whatever reason

**Comment by laurelhiatt** [comment]
PABPN1 citation 9 is just an 11, I think this is probably due to use of brackets somewhere

**Comment by laurelhiatt** [comment]
HSAN-VIII PRDM12 additional literature is just a blank pmid:

**Comment by laurelhiatt** [comment]
maybe we should replace PRNP  PMID: 29939637 (doesn't process) to Bookshelf ID: NBK507860?

**Comment by laurelhiatt** [comment]
SOX3 brackets I need to fix

**Comment by laurelhiatt** [comment]
empty PMID for pre-mir7-2_chng3

**Pull request merged**
