### PR TITLE
add citation.cff and version to website

### LINKED ISSUE #96: Append STRchive version number to files downloaded from `/loci/#downloads`
Currently, downloaded files look like this:

`hg19.STRchive-disease-loci.TRGT.BFiBXWeD.bed`

Would it be possible to append the current STRling version number to the filename so that users can keep track of file versions down the track? For example:

`hg19.STRchive-disease-loci.v2.0.2.TRGT.bed` (open to format suggestions)

I'd also want to generate something similar for all the files, including json, to attach to the release. I've just been doing this manually. For example: 
https://github.com/dashnowlab/STRchive/releases/tag/v1.2.0
Screenshot 2024-11-30 at 1 05 58 PM

### PR DESCRIPTION
**Pull request by vincerubinetti**
Closes #96 (partially)

- add citation.cff file as source of truth for version number, and for people wanting to conveniently cite the repo
- show version in header of site
- import version as global variable that can be used in any site code
- refactor defs/bed downloads and add version to download file name

### CODE REVIEW

**Comment by laurelhiatt** [comment]
it's beautiful :') @hdashnow do we want some flag for the ones that aren't displayed because of the gnomAD tag to be at the bottom instead of the absence of gnomAD plot, or leave for later?

**Review by laurelhiatt — APPROVED** [review]
urls fixed!

**Comment by vincerubinetti** [comment]
@laurelhiatt you may want to add yourself to the authors in citations.cff

**Comment by laurelhiatt** [comment]
@harriet what say ye? I think of it as my manuscript but your resource On Dec 2, 2024, at 2:15 PM, Vincent Rubinetti ***@***.***> wrote:﻿
@laurelhiatt you may want to add yourself to the authors in citations.cff

**Pull request merged**
