### PR TITLE
Add citation infra to website

### PR DESCRIPTION
**Pull request by vincerubinetti**
- add more comments throughout code base
- fix link component bug
- rename some components
- add "show more items" and "show more lines" components
- add glow animation on hash nav
- add truncate and truncate-lines css util classes
- on locus page:
  - change "references" to "links/identifiers"
  - get "references" and "additional_literature" fields from locus datum
  - add "cited" component which parses plain text for references in particular format and inserts superscript links
  - add age of onset details box
  - add "citation" component and use it at bottom of page for refs and additional lit sections

Note that this expects: 1) the presence of a `literature` field on the locus, 2) that free-text fields have citations in the format `[@doi:123456; @pmid:123456]`, 3) that `STRchive-citations.json` will replace `STRchive_literature_PMID.json` and `STRchive_PMID.json` and be in a particular format.

None of these things are true yet, so I put fake files in this PR just to test it. E.g. I only added `literature` to `DRPLA_ATN1`, so please go to that page to see an example.

### CODE REVIEW

**Comment by laurelhiatt** [comment]
Makes sense. That being said currently STRchive_literature_PMID.json is the output of the automated literature search for each locus (which we want to automate for every 3 months), which doesn’t pick up every citation that’s used in the locus pages. Are we adding additional citations to that search json, or does it make sense to have two distinct jsons? I remember us talking about adding to one json, but I don’t know the inner workings of manubot or what makes sense.

**Comment by vincerubinetti** [comment]
> STRchive_literature_PMID.json is the output of the automated literature search for each locus

I think we probably want to modify this existing script to do the following:

- do the search for each locus, but just save the ids e.g. `doi:123456`. for each locus, append the ids to the locus's `literature` field.
- scan all of `STRchive-database.json` for free text citations in the `[@doi:123456]` format we've been talking about, and extract all the ids. for each locus, append the extracted ids to the `literature` field.
- combine them into one list of ids, pass it to manubot, and export a single citations json file with title/authors/publisher/date/whatever for each
- save the changes to the `STRchive-database.json` file (`literature` fields)

**Comment by vincerubinetti** [comment]
Note: before merge, I need to revert the JSONs back to their original state so we don't accidentally leave in the fake data.

**Comment by laurelhiatt** [comment]
TBH i'm not sure about having a literature field within the json with all the publications, because Huntington for example has so many, I worry it'll get unwieldy (https://strchive.org/database/HTT.html). Would it make sense to make a separate json with matching IDs, like we discussed with the plots?

**Comment by vincerubinetti** [comment]
> TBH i'm not sure about having a literature field within the json with all the publications, because Huntington for example has so many, I worry it'll get unwieldy (https://strchive.org/database/HTT.html). Would it make sense to make a separate json with matching IDs, like we discussed with the plots?

Looks like there's about 1000 entries for that one. In the JSON, it would just be an array of short ids, but I guess people visually scanning through the JSON could get bogged down by this. I guess it depends how important you think it is for people parsing the JSON to have those ids right there, immediately, without having to cross reference anything (they'd still have to cross reference another file for the title/authors/etc though).

As I see it there's two options

Option 1:

```jsonc
[
  {
    "id": "SOME_LOCUS",
    // could be on order of thousands, maybe not "high-level" info anymore
    "literature": ["doi:12345", "pmid:12345"]
  }
]
```

```json
{
  "doi:12345": {
    "title": "lorem ipsum",
    "date": "2024-12-12",
    "link": "www.website.com"
  }
}
```


Option 2:

```jsonc
[
  {
    "id": "SOME_LOCUS",
  }
]
```

```json
{
  "doi:12345": {
    "title": "lorem ipsum",
    "date": "2024-12-12",
    "link": "www.website.com",
    "loci": ["SOME_LOCUS", "ANOTHER_LOCUS"]
  }
}
```

Either way we structure the JSON data under the hood, the website will still be displaying the same stuff... i.e. for Huntington we'll have 1k things to show somehow, which is a separate issue. I think I'll have to have some sort of search functionality for that, or at least hide some of it behind a "show more" button. This part will require some experimentation.

**Comment by vincerubinetti** [comment]
@laurelhiatt I pushed an update based on what we talked about yesterday. Can you take a quick look, then I will revert the JSON changes I made for testing and merge.

**Comment by laurelhiatt** [comment]
looks good to me! Only thing I might change is removing the "all" from "all additional literature", as I can't guarantee it is literally all literature for that locus

**Pull request merged**
