### PR TITLE
Add TAF1 XDP

### PR DESCRIPTION
**Pull request by hdashnow**
Add the TAF1 XDP locus. See #17 for details.
This replaces #4

### CODE REVIEW

**Review by laurelhiatt — CHANGES_REQUESTED** [review]
1. typ_age_onset_max is 60 whereas the text says 50, and then you have the year as 2007; I think it would make sense to be 2017 if that is when it was explicitly associated with a tandem repeat locus

**Comment by hdashnow** [comment]
> 1. typ_age_onset_max is 60 whereas the text says 50, and then you have the year as 2007; I think it would make sense to be 2017 if that is when it was explicitly associated with a tandem repeat locus

Thanks for picking up the age of onset issues. I have better described them. I used the average male and average female age of onset as the min and max of the typical range. Does that make sense? Or should I just make typical min/max ~40 since 99% of affected are male?

**Comment by laurelhiatt** [comment]
Since it’s the typical age of onset, I think it would make sense to make it the typical male case, but I understand your reasoning!

**Comment by laurelhiatt** [comment]
Webstr hg38 861907

**Comment by laurelhiatt** [comment]
webstr hg19 STR_1564408

**Pull request merged**
