### PR TITLE
Clean up STRchive scripts

### PR DESCRIPTION
**Pull request by hdashnow**
The goals of this PR are:

- [x] Incorporate fix from #92 (need to merge into a different branch so it gets included in the upcoming STRchive v2)
- [x] Rename all scripts for clarity and consistency
    - [x] `make_catalog.py` -> `make-catalog.py`
    - [x] `AutomatedLiterature.R` -> `get-literature.R` (see #84)
    - [x] `run_manubot.sh` -> `run-manubot.sh`
- [x] Delete scripts we no longer need:
    - [x] `clean_refs.py`
    - [x] `update_database.py` (useful content will be incorporated into `check-loci.py`)
    - [x] `reftogeneorientation.py` (useful content will be incorporated into `check-loci.py`)
- [x] Add a "linting" script for STRchive-database.json: `check-loci.py`
- [x] Extend the functionality of `make-catalog.py` to also generate arbitrary extended BED files
- [x] Update snakefile to match
- [x] Add some documentation
- [x] Delete `STRchive-database.csv`!

### CODE REVIEW

**Comment by hdashnow** [comment]
Sample output of:

`python make-catalog.py --format bed -g hg38 ../data/STRchive-database.json output.bed`

```
#chrom	start	stop	id	gene	pathogenic_motif_reference_orientation	pathogenic_min	inheritance	disease
chr1	1435798	1435818	HMNR7_VWA1	VWA1	GGCGCGGAGC	1	AR	Neuronopathy, distal hereditary motor, autosomal recessive 7
chr1	57367044	57367125	SCA37_DAB1	DAB1	GAAAT	31	AD	Spinocerebellar Ataxia Type 37
chr1	94418422	94418444	OPDM_ABCD3	ABCD3	GCC	118	AD	Oculopharyngodistal myopathy
chr1	149390803	149390842	NIID_NOTCH2NLC	NOTCH2NLC	GGC	66	AD	Neuronal intranuclear inclusion disease, Alzheimer disease and parkinsonism phenotype
```

Are these reasonable default columns?

**Comment by hdashnow** [comment]
Ready for review.

Remaining questions:
- Can `scripts/plots.R` be removed?
- Is it okay to delete `data/STRchive_literature_PMID.json`? I think this is no longer used. Any other files along these lines that are obsolete?
- Should we tidy up the data directory with additional subdirectories?
- Does the config for Snakemake need to be in the data directory? Suggest moving it to scripts.
- Should the snakemake command be reconfigured to run from the top-level directory? Might make it a bit easier.
- I'm not sure what to do about the biomaRt install issue (see `scripts/README.md`). It's going to make automation tricky.

**Comment by laurelhiatt** [comment]
The R script AutomatedLiterature.R is still necessary I believe, the python script just handles the output.

**Review by laurelhiatt — APPROVED** [review]
definitely can delete the PMID.json. let me see if I can figure out how to make biomart less annoying, but could maybe just run install within the R script?

**Comment by laurelhiatt** [comment]
oh yeah and we can move the snakemake config file and change the relative paths, I think that makes sense

**Comment by laurelhiatt** [comment]
I don't think I understand the conda/automated problem. can we make an R script specific yaml for the snakemake rule? would that help?

**Comment by vincerubinetti** [comment]
Just briefly looked at this, but weren't we going to rename "database" to "loci"? Other than that, glad to see all the file names are consistent!

**Comment by hdashnow** [comment]
> The R script AutomatedLiterature.R is still necessary I believe, the python script just handles the output.

Don't worry, it's still there. I just renamed it to get-literature.R for consistency.

> definitely can delete the PMID.json. let me see if I can figure out how to make biomart less annoying, but could maybe just run install within the R script?

Okay, I'll do that for now. It will just make it take longer to run because the install is slow. For some reason that is the only thing I can't get conda to install. 

> oh yeah and we can move the snakemake config file and change the relative paths, I think that makes sense

Shall I add that to this PR?

**Comment by hdashnow** [comment]
@vincerubinetti 
> Just briefly looked at this, but weren't we going to rename "database" to "loci"? Other than that, glad to see all the file names are consistent!

I'm happy to do that, but I just didn't want to break all your stuff. Can you please show me where it's defined for all the web stuff?

**Comment by laurelhiatt** [comment]
1.  the .py suffix above confused me but I get it now 2. Lit 3. Sure!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by hdashnow** [comment]
> 1. the .py suffix above confused me but I get it now 2. Lit 3. Sure! Get Outlook for iOS<https://aka.ms/o0ukef>


Oops! Typo in my comment. It's still R. Sory @laurelhiatt

**Comment by laurelhiatt** [comment]
I’ve never made a typo before in my life so I can’t imagine how this happened :/

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vincerubinetti** [comment]
There's a few places in `/site` where I import `STRchive-database.json` (and other json files). If you just rename them there too with a ctrl+f for the whole repo,. it should work.

**Pull request merged**
