### PR TITLE
Disease descriptions

### PR DESCRIPTION
**Pull request by hdashnow**
Add disease descriptions from mondo.

To do: 
- [ ] manually check them and add missing
- [x] fix json formatting

### CODE REVIEW

**Comment by hdashnow** [comment]
@laurelhiatt what do you think of adding disease descriptions? This is my first pass of grabbing many of them automatically.

**Comment by laurelhiatt** [comment]
I think it’s nice!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by laurelhiatt** [comment]
yo Harriet what's happening here? was maybe gonna do some edits with Tucci that overlap so

**Comment by hdashnow** [comment]
@laurelhiatt I've fixed this PR and it is ready to merge once you've checked it for errors. Note, 20 loci had no description in Mondo, so those are `null`.

**Comment by hdashnow** [comment]
@laurelhiatt I believe I've addressed all your comments. Merge if you're okay with it.

**Pull request merged**
