### PR TITLE
gnomAD data chart added - echarts

### PR DESCRIPTION
**Pull request by avvaruakshay**
- add gnomad plot data
- rename "plot" component to "box chart"
- add new "range chart" for gnomad frequency data
- css tweaks
- add page component for gnomad charts, with dropdown filter for sexes

### CODE REVIEW

**Review by laurelhiatt — APPROVED** [review]

**Comment by vincerubinetti** [comment]
Need to rework this PR, please don't merge.

**Comment by vincerubinetti** [comment]
@avvaruakshay Please take a look at my changes to the structure of the data. I put the top-level info for both sexes under its own `both_sexes` key to be consistent with the XX and XY. I also split the "counts" (# of samples?) out from the labels and put them in their own array. I also renamed the keys.

**Comment by avvaruakshay** [comment]
The JSON structure looks good! These customized plots look much better and consistent with the website design! 👍🏾

**Comment by avvaruakshay** [comment]
Awesome!! 💯

**Comment by avvaruakshay** [comment]
Should we now rebase and merge this PR?

**Comment by vincerubinetti** [comment]
I've already rebased. @laurelhiatt @hdashnow does this look okay to merge?

**Comment by laurelhiatt** [comment]
It looks fine to me! I don’t think we need the (both) designation for plots that aren’t sex-linked, and gnomAD is stylized with the lowercase first letter rather than GnomAD, but the overall plots and whatnot look great!

**Review by vincerubinetti — APPROVED** [review]

**Pull request merged**
