### PR TITLE
update R plots

### PR DESCRIPTION
**Pull request by hdashnow**
This is a temporary fix until we have properly automated this. Just to bring them up to date with the rest of the website.

### CODE REVIEW

**Review by laurelhiatt — APPROVED** [review]
thanks Harriet!

**Comment by vincerubinetti** [comment]
Just curious what this PR is intended to do. Note that since you're removing the JSON, this will remove the plots from the website. In fact I think the website will fail to build because I'm importing those JSONs and not doing a check to see if they're there.

**Comment by vincerubinetti** [comment]
In fact, I'm confused as to how Netlify was able to even build the site for the deploy preview. That's odd. Looking into it.

**Comment by vincerubinetti** [comment]
Sorry ignore me, I was reading the diff completely wrong. I thought you had deleted the JSON files, but really they just got put all on one line.

**Pull request merged**
