### PR TITLE
Set up basic site skeleton

### PR DESCRIPTION
**Pull request by vincerubinetti**
- delete files and folders that will not be relevant anymore: html templates, individual "database" pages, python scripts that generate html
- create new `/site` folder. move images to there.
- add basic webapp readme
- set up basic astro website
- redesign logo
- add basic skeleton/template for pages: header, main content, footer. add basic styling for content elements
- transfer over top-level static content from old/current website

### CODE REVIEW

**Comment by hdashnow** [comment]
Very nice!
I noticed that the footer links: Contact, Cite, Contribute, all point to the about page. Was this intended, or was this meant to jump to the specific corresponding section on the about page? Also fine if the answer is not implemented yet.

**Review by laurelhiatt — COMMENTED** [review]
I dig it.

**Comment by hdashnow** [comment]
I'd prefer to edit markdown for the static content if it's not too tricky/limiting.

**Comment by vincerubinetti** [comment]
> Very nice! I noticed that the footer links: Contact, Cite, Contribute, all point to the about page. Was this intended, or was this meant to jump to the specific corresponding section on the about page? Also fine if the answer is not implemented yet.

This was actually due to an [odd Netlify behavior/setting](https://answers.netlify.com/t/support-guide-how-can-i-alter-trailing-slash-behaviour-in-my-urls-will-enabling-pretty-urls-help/31191), and should be fixed now. 

> I'd prefer to edit markdown for the static content if it's not too tricky/limiting.

I've added the plugin for markdown support, and converted the resources page to use markdown instead. It wasn't difficult to set up. However, unless you plan on adding a lot more static content to the site (i.e. paragraphs of text, links, lists, etc), it won't be all that useful. That is, we'll need to use HTML in most other places because Markdown only can do simple formatting things.

**Pull request merged**
