### PR TITLE
Add more info to locus pages

### PR DESCRIPTION
**Pull request by vincerubinetti**
Addresses #60 

Note: `mechanism_detail` perhaps should be changed to `mechanism_details` in the data, to be consistent with e.g. `prevalence_details`

### CODE REVIEW

**Review by hdashnow — APPROVED** [review]
This looks awesome! I love how you've set up the ref and gene allele orientations and used "show more" for text fields.
Any thoughts on how to display the prevalence numerical value?

**Review by hdashnow — CHANGES_REQUESTED** [review]
Oops, I missed a bug the first time I looked.

If I go to this page: https://deploy-preview-61--strchive.netlify.app/loci/hfg_hoxa13-i/
then click on the next hox locus it's not redirecting correctly:
https://deploy-preview-61--strchive.netlify.app/loci/hfg_hoxa13-i/HFG_HOXA13-II

**Comment by vincerubinetti** [comment]
> prevalence

I just changed it to this, though maybe just a simple "X in N" is more appropriate.

Screenshot 2024-11-14 at 3 45 23 PM

**Review by hdashnow — APPROVED** [review]

**Comment by hdashnow** [comment]
Looks great to me :)

**Pull request merged**
