### PR TITLE
New STRchive JSON format for v2

### PR DESCRIPTION
**Pull request by hdashnow**
Making substantial and non-backwards compatible changes to the STRchive data JSON file format in preparation for STRchive v2 and new website release.
See https://github.com/dashnowlab/STRchive/issues/44

### CODE REVIEW

**Comment by hdashnow** [comment]
Still to do:
- [ ] choose format for tags
- [ ] make sure all delimiters are the same
- [ ] get the citations in a standard format (or keep this for a future PR?)

**Comment by hdashnow** [comment]
Shall I rebase this against the app branch @vincerubinetti ?

**Comment by vincerubinetti** [comment]
I will rebase my app branch onto main later/soon.

**Comment by hdashnow** [comment]
Okay. Let me know if you prefer I do this PR against yours first if you want to use the updated json format. It's pretty easy since I can really just edit 1-2 files.

**Comment by hdashnow** [comment]
Closing in favour of #58

**Pull request closed without merging**
